### ISSUE TITLE
Super takes at least 1 argument.

### ISSUE THREAD

**Issue by markgargan** [Granitosaurus/sauth#2]
Pretty cool tool! Alas when I tried it I got the following?
Python 2.7 Windows 10. 

TypeError: super() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "C:\devtools\Python27\lib\SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\devtools\Python27\lib\SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "C:\devtools\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "sauth.py", line 34, in __init__
    super().__init__(request, client_address, server)

**Comment by Granitosaurus** [comment]
sorry, sauth doesn't support python2
